# Generated by Django 4.1.8 on 2023-04-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(db_column='ID_CARGO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NOMBRE', max_length=20, null=True)),
            ],
            options={
                'db_table': 'CARGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cedula', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CEDULA', max_length=11, null=True, unique=True)),
                ('pasaporte', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='PASAPORTE', max_length=10, null=True, unique=True)),
                ('nombre1', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NOMBRE1', max_length=25, null=True)),
                ('nombre2', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NOMBRE2', max_length=25, null=True)),
                ('apellido1', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='APELLIDO1', max_length=25, null=True)),
                ('apellido2', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='APELLIDO2', max_length=25, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='FECHA_NACIMIENTO', null=True)),
                ('nacionalidad', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NACIONALIDAD', max_length=50, null=True)),
                ('tipo_sangre', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TIPO_SANGRE', max_length=3, null=True)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cedula', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CEDULA', max_length=11, null=True, unique=True)),
                ('nombre1', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NOMBRE1', max_length=25, null=True)),
                ('nombre2', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NOMBRE2', max_length=25, null=True)),
                ('apellido1', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='APELLIDO1', max_length=25, null=True)),
                ('apellido2', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='APELLIDO2', max_length=25, null=True)),
                ('username', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='USERNAME', max_length=20, null=True)),
                ('passw', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='PASSW', max_length=18, null=True)),
            ],
            options={
                'db_table': 'EMPLEADO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('aspecto_general', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='ASPECTO_GENERAL', null=True)),
                ('cabeza', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CABEZA', null=True)),
                ('cuello', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CUELLO', null=True)),
                ('corazon', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CORAZON', null=True)),
                ('torax', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TORAX', null=True)),
                ('abdomen', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='ABDOMEN', null=True)),
                ('genitales', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='GENITALES', null=True)),
                ('pulmones', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='PULMONES', null=True)),
                ('extremidades', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='EXTREMIDADES', null=True)),
                ('exam_neurol', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='EXAM_NEUROL', null=True)),
                ('tacto_rectal', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TACTO_RECTAL', null=True)),
                ('tacto_vaginal', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TACTO_VAGINAL', null=True)),
            ],
            options={
                'db_table': 'EXAMEN_FISICO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('cod_hospital', models.AutoField(db_column='COD_HOSPITAL', primary_key=True, serialize=False)),
                ('nombre_hosp', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NOMBRE_HOSP', max_length=25, null=True)),
                ('nombre_ceo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NOMBRE_CEO', max_length=40, null=True)),
                ('numero_fax', models.IntegerField(blank=True, db_column='NUMERO_FAX', null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='TELEFONO', null=True)),
                ('tipo_hospital', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TIPO_HOSPITAL', max_length=20, null=True)),
                ('api_key', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='API_KEY', max_length=30, null=True, unique=True)),
            ],
            options={
                'db_table': 'HOSPITAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('electrocardiograma', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='ELECTROCARDIOGRAMA', null=True)),
                ('rayosx', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='RAYOSX', null=True)),
                ('sonografia', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='SONOGRAFIA', null=True)),
                ('tomografia_axial', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TOMOGRAFIA_AXIAL', null=True)),
                ('diagnostico', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='DIAGNOSTICO', null=True)),
                ('fecha', models.DateField(blank=True, db_column='FECHA', null=True)),
            ],
            options={
                'db_table': 'IMAGENES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Placas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('foto', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='FOTO', null=True)),
            ],
            options={
                'db_table': 'PLACAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('cod_registro', models.AutoField(db_column='COD_REGISTRO', primary_key=True, serialize=False)),
                ('motivo', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='MOTIVO', null=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, db_column='FECHA_LLEGADA', null=True)),
                ('fechahora_clasificacion', models.DateTimeField(blank=True, db_column='FECHAHORA_CLASIFICACION', null=True)),
                ('fechahora_final', models.DateTimeField(blank=True, db_column='FECHAHORA_FINAL', null=True)),
                ('enfermedad', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='ENFERMEDAD', max_length=60, null=True)),
            ],
            options={
                'db_table': 'REGISTRO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, db_column='NUMERO', null=True)),
            ],
            options={
                'db_table': 'TELEFONO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTelefono',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TIPO', max_length=30, null=True)),
            ],
            options={
                'db_table': 'TIPO_TELEFONO',
                'managed': False,
            },
        ),
    ]
